from sqlalchemy import Column, Integer, Float, String, Boolean
from .database import Base


class Calculation(Base):
    __tablename__ = "calculations"

    id = Column(Integer, primary_key=True, index=True)
    # Input fields
    long_side_1 = Column(Float)
    long_side_2 = Column(Float)
    long_side_3 = Column(Float)
    long_side_2_1 = Column(Float)
    long_side_3_1 = Column(Float)
    short_side_1 = Column(Float)
    short_side_2 = Column(Float)
    short_side_3 = Column(Float)
    short_side_2_1 = Column(Float)
    short_side_3_1 = Column(Float)
    quantity_cons = Column(Integer)
    quantity_nodes = Column(Integer)
    quantity_uts = Column(Integer)
    holder_a_side = Column(Float)
    holder_b_side = Column(Float)
    wind_area = Column(String)
    local_type = Column(String)
    h_max = Column(Float)
    aero_coff = Column(Float)
    koef_safety = Column(Float)
    overpressure_opening = Column(Float)
    wall_thickness = Column(Float)
    hole_overlap = Column(Float)
    len_to_centre_construction = Column(Float)
    alpha_koef = Column(Float)
    construction_oriented = Column(String)
    lsk_name = Column(String)

    # Results fields
    long_side_usefull = Column(Float)
    short_side_usefull = Column(Float)
    long_window = Column(Float)
    short_window = Column(Float)
    s_hole = Column(Float)
    s_window = Column(Float)
    s_usefull = Column(Float)
    s_effictive_1 = Column(Float)
    s_effictive_wind_max = Column(Float)
    p_min = Column(Float)
    p_max = Column(Float)
    w_0 = Column(Float)
    wind_peak_load = Column(Float)
    k_koef = Column(Float)
    ripple_ratio = Column(Float)
    correlation_coff = Column(Float)
    angle_a = Column(Float)
    sling_len_work = Column(Float)
    len_between_nodes = Column(Float)
    warning = Column(String)
    warning_2 = Column(String)
    warning_angle_value = Column(String)